// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://gywziyfygtrjocevpnut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5d3ppeWZ5Z3Ryam9jZXZwbnV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk4NjI3NjMsImV4cCI6MjA4NTQzODc2M30.XyiHxTtsgoMNH3nL1QW-ajJrEpTbUs1yPN0mq_VLt2M";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);